// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="RosenbrockSimulator,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=17.250600,HLS_SYN_LAT=34,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=592,HLS_SYN_FF=39988,HLS_SYN_LUT=22918}" *)

module RosenbrockSimulator (
        clk,
        reset,
        startSimulation,
        simulationDone,
        a,
        b,
        chromosome_in,
        fitness
);


input   clk;
input   reset;
input   startSimulation;
output   simulationDone;
input  [31:0] a;
input  [31:0] b;
input  [63:0] chromosome_in;
output  [31:0] fitness;

reg simulationDone;
reg[31:0] fitness;

wire    grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone;
wire    grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone_ap_vld;
wire   [31:0] grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness;
wire    grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness_ap_vld;
wire   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;

RosenbrockSimulator_simulateRosenbrock grp_RosenbrockSimulator_simulateRosenbrock_fu_88(
    .ap_clk(clk),
    .ap_rst(reset),
    .startSimulation(startSimulation),
    .simulationDone(grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone),
    .simulationDone_ap_vld(grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone_ap_vld),
    .a(a),
    .b(b),
    .chromosome_in(chromosome_in),
    .fitness(grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness),
    .fitness_ap_vld(grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness_ap_vld)
);

always @ (posedge clk) begin
    if ((1'b1 == grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness_ap_vld)) begin
        fitness <= grp_RosenbrockSimulator_simulateRosenbrock_fu_88_fitness;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone_ap_vld)) begin
        simulationDone <= grp_RosenbrockSimulator_simulateRosenbrock_fu_88_simulationDone;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

endmodule //RosenbrockSimulator
