// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _GenerationGenerator_consumeRandom_HH_
#define _GenerationGenerator_consumeRandom_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct GenerationGenerator_consumeRandom : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<24> > random;
    sc_in< sc_lv<24> > GenerationGenerator_randomNumberIndex_V_i;
    sc_out< sc_lv<24> > GenerationGenerator_randomNumberIndex_V_o;
    sc_out< sc_logic > GenerationGenerator_randomNumberIndex_V_o_ap_vld;
    sc_out< sc_lv<8> > GenerationGenerator_randomNumbers_V_address0;
    sc_out< sc_logic > GenerationGenerator_randomNumbers_V_ce0;
    sc_out< sc_logic > GenerationGenerator_randomNumbers_V_we0;
    sc_out< sc_lv<24> > GenerationGenerator_randomNumbers_V_d0;
    sc_in< sc_lv<24> > GenerationGenerator_randomNumbers_V_q0;


    // Module declarations
    GenerationGenerator_consumeRandom(sc_module_name name);
    SC_HAS_PROCESS(GenerationGenerator_consumeRandom);

    ~GenerationGenerator_consumeRandom();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<24> > val_V_reg_223;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<24> > GenerationGenerator_s_reg_229;
    sc_signal< sc_lv<9> > tmp_s_fu_183_p2;
    sc_signal< sc_lv<9> > tmp_21_phi_fu_156_p4;
    sc_signal< sc_lv<1> > tmp_fu_173_p2;
    sc_signal< sc_lv<32> > tmp_29_cast_fu_190_p1;
    sc_signal< sc_lv<32> > tmp_23_fu_200_p1;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_22_fu_195_p2;
    sc_signal< sc_lv<25> > lhs_V_cast_fu_163_p1;
    sc_signal< sc_lv<25> > r_V_fu_167_p2;
    sc_signal< sc_lv<9> > tmp_13_fu_179_p1;
    sc_signal< sc_lv<1> > tmp_24_fu_204_p2;
    sc_signal< sc_lv<24> > tmp_25_fu_209_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<9> ap_const_lv9_17;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<25> ap_const_lv25_1FFFFFF;
    static const sc_lv<25> ap_const_lv25_18;
    static const sc_lv<9> ap_const_lv9_1FF;
    static const sc_lv<24> ap_const_lv24_17;
    static const sc_lv<24> ap_const_lv24_1;
    static const sc_lv<24> ap_const_lv24_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_GenerationGenerator_randomNumberIndex_V_o();
    void thread_GenerationGenerator_randomNumberIndex_V_o_ap_vld();
    void thread_GenerationGenerator_randomNumbers_V_address0();
    void thread_GenerationGenerator_randomNumbers_V_ce0();
    void thread_GenerationGenerator_randomNumbers_V_d0();
    void thread_GenerationGenerator_randomNumbers_V_we0();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_lhs_V_cast_fu_163_p1();
    void thread_r_V_fu_167_p2();
    void thread_tmp_13_fu_179_p1();
    void thread_tmp_21_phi_fu_156_p4();
    void thread_tmp_22_fu_195_p2();
    void thread_tmp_23_fu_200_p1();
    void thread_tmp_24_fu_204_p2();
    void thread_tmp_25_fu_209_p2();
    void thread_tmp_29_cast_fu_190_p1();
    void thread_tmp_fu_173_p2();
    void thread_tmp_s_fu_183_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
