// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _GenerationGenerator_produceRandom_HH_
#define _GenerationGenerator_produceRandom_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct GenerationGenerator_produceRandom : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<24> > random;
    sc_in< sc_lv<24> > GenerationGenerator_randomNumberIndex_V_i;
    sc_out< sc_lv<24> > GenerationGenerator_randomNumberIndex_V_o;
    sc_out< sc_logic > GenerationGenerator_randomNumberIndex_V_o_ap_vld;
    sc_out< sc_lv<8> > GenerationGenerator_randomNumbers_V_address0;
    sc_out< sc_logic > GenerationGenerator_randomNumbers_V_ce0;
    sc_out< sc_logic > GenerationGenerator_randomNumbers_V_we0;
    sc_out< sc_lv<24> > GenerationGenerator_randomNumbers_V_d0;


    // Module declarations
    GenerationGenerator_produceRandom(sc_module_name name);
    SC_HAS_PROCESS(GenerationGenerator_produceRandom);

    ~GenerationGenerator_produceRandom();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<24> > val_V_reg_156;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > tmp_fu_130_p1;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_1_fu_135_p2;
    sc_signal< sc_lv<24> > tmp_2_fu_141_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<24> ap_const_lv24_17;
    static const sc_lv<24> ap_const_lv24_1;
    static const sc_lv<24> ap_const_lv24_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_GenerationGenerator_randomNumberIndex_V_o();
    void thread_GenerationGenerator_randomNumberIndex_V_o_ap_vld();
    void thread_GenerationGenerator_randomNumbers_V_address0();
    void thread_GenerationGenerator_randomNumbers_V_ce0();
    void thread_GenerationGenerator_randomNumbers_V_d0();
    void thread_GenerationGenerator_randomNumbers_V_we0();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_tmp_1_fu_135_p2();
    void thread_tmp_2_fu_141_p2();
    void thread_tmp_fu_130_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
