// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xgenerationgenerator.h"

extern XGenerationgenerator_Config XGenerationgenerator_ConfigTable[];

XGenerationgenerator_Config *XGenerationgenerator_LookupConfig(u16 DeviceId) {
	XGenerationgenerator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XGENERATIONGENERATOR_NUM_INSTANCES; Index++) {
		if (XGenerationgenerator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XGenerationgenerator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XGenerationgenerator_Initialize(XGenerationgenerator *InstancePtr, u16 DeviceId) {
	XGenerationgenerator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XGenerationgenerator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XGenerationgenerator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

