webtalk_init -webtalk_dir C:\\Users\\cml\\Desktop\\GeneticAlgoVivado\\GeneticAlgoVivado.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-14 14:39:24" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "598om12e7jf04ss1pe2of2hq2e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1544792881848" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key hwid -value "1544790320124" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key bspid -value "1544791648273" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key projSize -value "203.35546875" -context "sdk\\\\application/1544792881848"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1544794764288"
webtalk_transmit -clientid 3858070818 -regid "" -xml C:\\Users\\cml\\Desktop\\GeneticAlgoVivado\\GeneticAlgoVivado.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\cml\\Desktop\\GeneticAlgoVivado\\GeneticAlgoVivado.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\cml\\Desktop\\GeneticAlgoVivado\\GeneticAlgoVivado.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
