# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.2
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fpo_v7_0"

set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/opencv"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fft_v9_0"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fir_v7_0"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/dds_v6_0"

source check_sim.tcl


# --> systemc simulation

ap_puts_info "COSIM" 11 "Starting SystemC simulation ..."

cd ../systemc

# remove hdltvin&hdltvout in tv dir
file delete -force [file join "../tv" GenerationGenerator.hdltvin.dat]
file delete -force [file join "../tv" GenerationGenerator.hdltvout.dat]

set ::env(AP_WRITE_TV) "on"

file delete -force  "err.log"

if {![file exists cosim.sc.exe]} {
	ap_puts_err "COSIM" 321 " EXE file generate failed, please re-run cosim."
	return -code error -errorcode $::errorCode
}

set ret [catch {eval exec ./cosim.sc.exe | tee temp1.log >&@ stdout} err]

if {$ret == 1} {
	ap_puts_err "COSIM" 344 "Rtl simulation failed."
	return -code error -errorcode $::errorCode
}

if {[file isfile GenerationGenerator.hdltvin.dat]} {
	file copy -force GenerationGenerator.hdltvin.dat [file join "../tv" GenerationGenerator.hdltvin.dat]
}
if {[file isfile GenerationGenerator.hdltvout.dat]} {
	file copy -force GenerationGenerator.hdltvout.dat [file join "../tv" GenerationGenerator.hdltvout.dat]
}

sc_sim_check $ret $err "temp1.log"

# --> verilog simulation

ap_puts_info "COSIM" 323 "Starting verilog simulation..."

ap_puts_info "COSIM" 15 "Starting Modelsim ..."

cd ../verilog

if {![file exists [file join "../tv" GenerationGenerator.hdltvin.dat]]} {
	ap_puts_err "COSIM" 332 "Test Vector GenerationGenerator.hdltvin.dat in /tv dir doesn't exist."
	return -code error -errorcode $::errorCode
}

file copy -force [file join "../tv" GenerationGenerator.hdltvin.dat] GenerationGenerator.hdltvin.dat

file copy -force [file join "../tv" GenerationGenerator.hdltvout.dat] GenerationGenerator.hdltvout.dat

file delete -force ".exit.err"
file delete -force ".aesl_error"
file delete -force "err.log"

if {[file isfile compile_modelsim.sh]} {
	catch {eval exec sh ./compile_modelsim.sh >&@ stdout} err

	if {$err != ""} {
		ap_puts_err "COSIM" 306 "Failed in preprocessing test bench: $err"
		return -code error -errorcode $::errorCode
	}
}

set ret [catch {eval exec "vsim -c -do cosim.modelsim.scr | tee temp2.log" >@ stdout} err]
