// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GenerationGenerator,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.594667,HLS_SYN_LAT=68,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1230,HLS_SYN_LUT=998}" *)

module GenerationGenerator (
        clk,
        reset,
        startGenerating,
        generatingDone,
        generation_parent1,
        generation_parent2,
        generation_child1,
        generation_child2,
        mutation_probability,
        random
);


input   clk;
input   reset;
input   startGenerating;
output   generatingDone;
input  [63:0] generation_parent1;
input  [63:0] generation_parent2;
output  [63:0] generation_child1;
output  [63:0] generation_child2;
input  [23:0] mutation_probability;
input  [23:0] random;

reg generatingDone;
reg[63:0] generation_child1;
reg[63:0] generation_child2;

reg   [7:0] GenerationGenerator_randomNumbers_V_address0;
reg    GenerationGenerator_randomNumbers_V_ce0;
wire   [23:0] GenerationGenerator_randomNumbers_V_q0;
wire   [0:0] GenerationGenerator_s_load_fu_174_p1;
wire   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_GenerationGenerator_generateGeneration_fu_114_generatingDone;
wire    grp_GenerationGenerator_generateGeneration_fu_114_generatingDone_ap_vld;
wire   [63:0] grp_GenerationGenerator_generateGeneration_fu_114_generation_child1;
wire    grp_GenerationGenerator_generateGeneration_fu_114_generation_child1_ap_vld;
wire   [63:0] grp_GenerationGenerator_generateGeneration_fu_114_generation_child2;
wire    grp_GenerationGenerator_generateGeneration_fu_114_generation_child2_ap_vld;
wire   [23:0] grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o;
wire    grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o_ap_vld;
wire   [7:0] grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_address0;
wire    grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_ce0;
wire   [23:0] grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o;
wire    grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o_ap_vld;
wire   [7:0] grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_address0;
wire    grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_ce0;
wire    grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_we0;
wire   [23:0] grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_d0;
wire    ap_CS_fsm_state2;
reg   [23:0] GenerationGenerator_randomNumberIndex_V;
reg   [23:0] GenerationGenerator_trueRandomIndex_V;
wire   [0:0] GenerationGenerator_1_load_fu_178_p1;

GenerationGeneratbkb #(
    .DataWidth( 24 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
GenerationGenerator_randomNumbers_V_U(
    .clk(clk),
    .reset(reset),
    .address0(GenerationGenerator_randomNumbers_V_address0),
    .ce0(GenerationGenerator_randomNumbers_V_ce0),
    .we0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_we0),
    .d0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_d0),
    .q0(GenerationGenerator_randomNumbers_V_q0)
);

GenerationGenerator_generateGeneration grp_GenerationGenerator_generateGeneration_fu_114(
    .ap_clk(clk),
    .ap_rst(reset),
    .startGenerating(startGenerating),
    .generatingDone(grp_GenerationGenerator_generateGeneration_fu_114_generatingDone),
    .generatingDone_ap_vld(grp_GenerationGenerator_generateGeneration_fu_114_generatingDone_ap_vld),
    .generation_parent1(generation_parent1),
    .generation_parent2(generation_parent2),
    .generation_child1(grp_GenerationGenerator_generateGeneration_fu_114_generation_child1),
    .generation_child1_ap_vld(grp_GenerationGenerator_generateGeneration_fu_114_generation_child1_ap_vld),
    .generation_child2(grp_GenerationGenerator_generateGeneration_fu_114_generation_child2),
    .generation_child2_ap_vld(grp_GenerationGenerator_generateGeneration_fu_114_generation_child2_ap_vld),
    .mutation_probability(mutation_probability),
    .GenerationGenerator_trueRandomIndex_V_i(GenerationGenerator_trueRandomIndex_V),
    .GenerationGenerator_trueRandomIndex_V_o(grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o),
    .GenerationGenerator_trueRandomIndex_V_o_ap_vld(grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o_ap_vld),
    .GenerationGenerator_randomNumbers_V_address0(grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_address0),
    .GenerationGenerator_randomNumbers_V_ce0(grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_ce0),
    .GenerationGenerator_randomNumbers_V_q0(GenerationGenerator_randomNumbers_V_q0)
);

GenerationGenerator_consumeRandom grp_GenerationGenerator_consumeRandom_fu_144(
    .ap_clk(clk),
    .ap_rst(reset),
    .random(random),
    .GenerationGenerator_randomNumberIndex_V_i(GenerationGenerator_randomNumberIndex_V),
    .GenerationGenerator_randomNumberIndex_V_o(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o),
    .GenerationGenerator_randomNumberIndex_V_o_ap_vld(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o_ap_vld),
    .GenerationGenerator_randomNumbers_V_address0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_address0),
    .GenerationGenerator_randomNumbers_V_ce0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_ce0),
    .GenerationGenerator_randomNumbers_V_we0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_we0),
    .GenerationGenerator_randomNumbers_V_d0(grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_d0)
);

always @ (posedge clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'd0 == GenerationGenerator_s_load_fu_174_p1) & (1'd0 == GenerationGenerator_1_load_fu_178_p1))) begin
        GenerationGenerator_randomNumberIndex_V <= 24'd0;
    end else if ((1'b1 == grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o_ap_vld)) begin
        GenerationGenerator_randomNumberIndex_V <= grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumberIndex_V_o;
    end
end

always @ (posedge clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'd0 == GenerationGenerator_s_load_fu_174_p1) & (1'd0 == GenerationGenerator_1_load_fu_178_p1))) begin
        GenerationGenerator_trueRandomIndex_V <= 24'd0;
    end else if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o_ap_vld)) begin
        GenerationGenerator_trueRandomIndex_V <= grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_trueRandomIndex_V_o;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_generatingDone_ap_vld)) begin
        generatingDone <= grp_GenerationGenerator_generateGeneration_fu_114_generatingDone;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_generation_child1_ap_vld)) begin
        generation_child1 <= grp_GenerationGenerator_generateGeneration_fu_114_generation_child1;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_generation_child2_ap_vld)) begin
        generation_child2 <= grp_GenerationGenerator_generateGeneration_fu_114_generation_child2;
    end
end

always @ (*) begin
    if ((1'b1 == grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_ce0)) begin
        GenerationGenerator_randomNumbers_V_address0 = grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_address0;
    end else if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_ce0)) begin
        GenerationGenerator_randomNumbers_V_address0 = grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_address0;
    end else begin
        GenerationGenerator_randomNumbers_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_ce0)) begin
        GenerationGenerator_randomNumbers_V_ce0 = grp_GenerationGenerator_consumeRandom_fu_144_GenerationGenerator_randomNumbers_V_ce0;
    end else if ((1'b1 == grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_ce0)) begin
        GenerationGenerator_randomNumbers_V_ce0 = grp_GenerationGenerator_generateGeneration_fu_114_GenerationGenerator_randomNumbers_V_ce0;
    end else begin
        GenerationGenerator_randomNumbers_V_ce0 = 'bx;
    end
end

assign GenerationGenerator_1_load_fu_178_p1 = 1'd0;

assign GenerationGenerator_s_load_fu_174_p1 = 1'd0;

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

endmodule //GenerationGenerator
